source 'https://rubygems.org'

gem "jekyll-remote-theme"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
    gem "github-pages"
    gem "jekyll-data"
    gem "jekyll-include-cache"
end
gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem 'html-proofer'